name: Subida a Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  subir-a-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-proyecto:latest .

      - name: Subir imagen Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-proyecto:latest
