name: Subida a Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  subir-a-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Construir imagen Docker con múltiples etiquetas
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/mi-proyecto:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/mi-proyecto:worker \
            .

      - name: Subir imagen Docker (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-proyecto:latest

      - name: Subir imagen Docker (worker)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-proyecto:worker
